"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

plist = dict(CFBundleDocumentTypes=[dict(CFBundleTypeExtensions=["csv"],
                                         CFBundleTypeName="CSV Document",
                                         CFBundleTypeRole="Viewer"),
                                    ]
             )

options = {
           'argv_emulation': True,
           'plist': plist,
           'iconfile':'assets/hotdog.icns',
          }

setup(
    py_modules=[],
    app=['src/picklist_gen.py'],
    data_files=[('assets', ['assets/products_export.csv'])],
    options={'py2app': options},
    setup_requires=['py2app'],
    version='0.3.1',
)
