"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

Plist = dict(CFBundleDocumentTypes=[dict(CFBundleTypeExtensions=["csv"],
                                         CFBundleTypeName="CSV Document",
                                         CFBundleTypeRole="Viewer"),
                                    ]
             )
APP = ['vaseline.py']
DATA_FILES = ['products_export.csv']
OPTIONS = {'argv_emulation': True,
           'plist': Plist,
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
